#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

cd $PWD

if [ -z $1 ]
then
  FILES='*.pdf'
else
  if [ ! -e $1 ]
  then
    echo NOT FOUND $1
    exit 1
  else
    FILES=$1
  fi
fi

if [ -z $2 ]
then
  PAGE=0
else
  PAGE=$2
fi

find -type f -iname "$FILES" | while read FILE
do
  echo $FILE
  PNG=$(echo $FILE | sed s/.pdf/.png/g)
  convert -thumbnail x200 -flatten $FILE[$PAGE] $PNG
done

